### ISSUE TITLE
When will this be available on mainnnet? 

### ISSUE THREAD

**Issue by garvitgoel** [Lightprotocol/groth16-solana#4]
Hi guys,

This is Garvit from Electron. Thanks for doing this awesome work here. We are interested in using this, and just wondering if you are aware of any timeline on when this will be available on mainnet? 

And is there any stop gap solution meanwhile?

**Comment by weikengchen** [comment]
It seems that this has already been available on the mainnet (aka mainnet beta) since mainnet is in v1.16 now.

**Comment by weikengchen** [comment]
Ok. Correction. Someone from Elusiv told me that you need to wait until the end of the year.

**Comment by ananas-block** [comment]
The feature is still not active on mainnet, probably March/April. You can already use it on devnet.
